[package]
name = "zero2prod"
version = "0.1.0"
author = "Rayene Nassim Zorgani <jr_zorgani@esi.dz>"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4.3.1"
reqwest = "0.11.16"
serde = {version = "1.0.159", features=["derive"]}
sqlx-cli = { version = "0.6.3", default-features = false, features = ["postgres"] }
tokio ={version = "1.27.0", features= ["macros", "rt-multi-thread"]}



