application:
  port: 8000
database:
  host: "172.17.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "jr_zorgani@esi.dz"
