application:
  port: 8000
database:
  host: "172.17.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://127.0.0.1:8000"
  sender_email: "jr_zorgani@esi.dz"
  authorization_token: "a6b37f0c-b388-4f5b-b22d-3f5127196be0"
  timeout_milliseconds: 10000
